MyRestaurantApp/MyRestaurantApp/Models/LoginViewModel.cs
namespace MyRestaurantApp.Models
{
    public class LoginViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

MyRestaurantApp/MyRestaurantApp/Models/RegisterViewModel.cs
namespace MyRestaurantApp.Models
{
    public class RegisterViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}

MyRestaurantApp/MyRestaurantApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
// using MyRestaurantApp.Data;
// using MyRestaurantApp.Models;

using RestoRunner.Entities;
// using RestoRunner.Entities.AuthMicroservice;

namespace MyRestaurantApp.Controllers
{
    public class AccountController : Controller
    {
        private readonly RestoRunnerDbContext _context;

        public AccountController(RestoRunnerDbContext context)
        {
            _context = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var user = _context.Users.SingleOrDefault(u => u.Username == username && u.Password == password);
            if (user != null)
            {
                // Authentificate user
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Show error message
                return View();
            }
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            _context.Users.Add(user);
            _context.SaveChanges();
            return RedirectToAction("Login");
        }
    }
}

MyRestaurantApp/MyRestaurantApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RestaurantMenu.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyRestaurantApp/MyRestaurantApp/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
// using MyRestaurantApp.Data;
using RestoRunner.Entities;

namespace MyRestaurantApp.Controllers
{
    public class MenuController : Controller
    {
        private readonly RestoRunnerDbContext _context;

        public MenuController(RestoRunnerDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var menuItems = _context.MenuItems.ToList();
            return View(menuItems);
        }
    }
}

MyRestaurantApp/MyRestaurantApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
// using MyRestaurantApp.Data;
// using MyRestaurantApp.Models;
using RestoRunner.Entities;
// using RestoRunner.Entities.OrderMicroservice;
// using RestoRunner.Entities.AuthMicroservice;

namespace MyRestaurantApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly RestoRunnerDbContext _context;

        public OrderController(RestoRunnerDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var userId = GetCurrentUserId(); // Get the current user's ID
            var orders = _context.Orders.Where(o => o.CustomerId == userId).ToList();
            return View(orders);
        }

        public IActionResult Create()
        {
            var menuItems = _context.MenuItems.ToList();
            return View(menuItems);
        }

        [HttpPost]
        public IActionResult Create(List<int> menuItemIds, List<int> quantities)
        {
            var userId = GetCurrentUserId(); // Get the current user's ID
            var order = new Order
            {
                CustomerId = userId,
                OrderDate = DateTime.Now,
                OrderItems = new List<OrderItem>()
            };

            decimal totalPrice = 0;
            for (int i = 0; i < menuItemIds.Count; i++)
            {
                var menuItem = _context.MenuItems.Find(menuItemIds[i]);
                var orderItem = new OrderItem
                {
                    MenuItemId = menuItemIds[i],
                    Quantity = quantities[i],
                    MenuItem = menuItem
                };
                order.OrderItems.Add(orderItem);
                totalPrice += menuItem.Price * quantities[i];
            }

            order.TotalPrice = totalPrice;
            _context.Orders.Add(order);
            _context.SaveChanges();

            return RedirectToAction("Payment", new { orderId = order.Id });
        }

        public IActionResult Payment(int orderId)
        {
            var order = _context.Orders.Include(o => o.OrderItems).ThenInclude(oi => oi.MenuItem).SingleOrDefault(o => o.Id == orderId);
            return View(order);
        }

        [HttpPost]
        public IActionResult Payment(int orderId, string paymentMethod)
        {
            // Process payment
            // ...

            return RedirectToAction("Success", new { orderId = orderId });
        }

        public IActionResult Success(int orderId)
        {
            var order = _context.Orders.Include(o => o.OrderItems).ThenInclude(oi => oi.MenuItem).SingleOrDefault(o => o.Id == orderId);
            return View(order);
        }

        private int GetCurrentUserId()
        {
            // Get the current user's ID from the authenticated user
            // ...
            return 1; // For example purposes
        }
    }
}

MyRestaurantApp/MyRestaurantApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Домашняя страница";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать в наш ресторан!</h1>
    <p>Здесь вы можете просмотреть наше меню и сделать заказ.</p>
    <p>
        <a asp-controller="Menu" asp-action="Index">Перейти к меню</a>
    </p>
</div>

MyRestaurantApp/MyRestaurantApp/Views/Menu/Index.cshtml
@model IEnumerable<MenuItem>
@{
    ViewData["Title"] = "Меню ресторана";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Меню ресторана</h1>

<form method="post" asp-action="PlaceOrder">
    <table class="table">
        <thead>
            <tr>
                <th>Блюдо</th>
                <th>Описание</th>
                <th>Цена</th>
                <th>Количество</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>@item.Price.ToString("C")</td>
                    <td><input type="number" name="orderItems[@item.Id].Quantity" value="0" min="0" /></td>
                    <input type="hidden" name="orderItems[@item.Id].MenuItemId" value="@item.Id" />
                </tr>
            }
        </tbody>
    </table>
    <div class="form-group">
        <label for="customerName">Имя:</label>
        <input type="text" class="form-control" name="customerName" id="customerName" required />
    </div>
    <button type="submit" class="btn btn-primary">Оформить заказ</button>
</form>

MyRestaurantApp/MyRestaurantApp/Views/Order/Create.cshtml
@model IEnumerable<MenuItem>

<h2>Create Order</h2>
<form asp-controller="Order" asp-action="Create" method="post">
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    <td>@Model.ElementAt(i).Name</td>
                    <td>
                        <input type="hidden" name="menuItemIds" value="@Model.ElementAt(i).Id" />
                        <input type="number" name="quantities" min="0" value="0" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button type="submit">Place Order</button>
</form>

MyRestaurantApp/MyRestaurantApp/Views/Order/Payment.cshtml
@model Order

<h2>Payment</h2>
<table>
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
            <tr>
                <td>@item.MenuItem.Name</td>
                <td>@item.Quantity</td>
                <td>@((item.MenuItem.Price * item.Quantity).ToString("C"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Total:</td>
            <td>@Model.TotalPrice.ToString("C")</td>
        </tr>
    </tfoot>
</table>

<form asp-controller="Order" asp-action="Payment" method="post">
    <input type="hidden" name="orderId" value="@Model.Id" />
    <div>
        <label>Payment Method:</label>
        <select name="paymentMethod">
            <option value="CreditCard">Credit Card</option>
            <option value="PayPal">PayPal</option>
        </select>
    </div>
    <button type="submit">Pay</button>
</form>

MyRestaurantApp/MyRestaurantApp/Views/Order/Success.cshtml
@model Order

<h2>Order Placed Successfully</h2>
<p>Thank you for your order!</p>

<h3>Order Details</h3>
<table>
    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
            <tr>
                <td>@item.MenuItem.Name</td>
                <td>@item.Quantity</td>
                <td>@((item.MenuItem.Price * item.Quantity).ToString("C"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Total:</td>
            <td>@Model.TotalPrice.ToString("C")</td>
        </tr>
    </tfoot>
</table>

MyRestaurantApp/MyRestaurantApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyRestaurantApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyRestaurantApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyRestaurantApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>